import { StyleSheet, Platform, Dimensions } from "react-native";
import { colors } from "../styles/colors";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  background: {
    flex: 1,
    width: "100%",
    height: "100%",
    backgroundColor: colors.light,
  },
  header: {
    height: height * 0.12,
    backgroundColor: colors.dark,
    justifyContent: "center",
    alignItems: "center",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  headerTitle: {
    color: colors.primary,
    fontSize: width * 0.06,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingVertical: height * 0.025,
    paddingHorizontal: width * 0.04,
  },
  overlay: {
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    padding: width * 0.05,
    borderRadius: 25,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    backdropFilter: "blur(10px)",
  },
  title: {
    color: colors.dark,
    fontWeight: "700",
    fontSize: width * 0.065,
    textAlign: "center",
    marginBottom: height * 0.02,
    letterSpacing: 0.6,
    textShadowColor: "rgba(0, 0, 0, 0.1)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  input: {
    backgroundColor: colors.white,
    borderRadius: 50, // Дугуй хэлбэр
    paddingVertical: height * 0.015,
    paddingHorizontal: width * 0.05,
    fontSize: width * 0.04,
    color: colors.dark,
    borderWidth: 1,
    borderColor: colors.gray,
    width: "85%",
    marginBottom: height * 0.012,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: colors.gray,
    marginBottom: height * 0.012,
    width: "85%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  passwordInput: {
    flex: 1,
    paddingVertical: height * 0.015,
    paddingHorizontal: width * 0.05,
    fontSize: width * 0.04,
    color: colors.dark,
  },
  eyeIcon: {
    padding: width * 0.03,
  },
  button: {
    backgroundColor: colors.primary,
    paddingVertical: height * 0.018,
    paddingHorizontal: width * 0.08,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    width: "70%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 7,
    marginVertical: height * 0.01,
  },
  buttonText: {
    color: colors.dark,
    fontWeight: "700",
    fontSize: width * 0.04,
    letterSpacing: 0.3,
  },
  link: {
    color: colors.accent,
    fontWeight: "500",
    fontSize: width * 0.032,
    textDecorationLine: "underline",
    marginTop: height * 0.01,
  },
  errorText: {
    color: colors.danger,
    fontSize: width * 0.028,
    marginBottom: height * 0.008,
    textAlign: "center",
    width: "85%",
  },
  dashboardItem: {
    backgroundColor: colors.white,
    padding: width * 0.04,
    borderRadius: 20,
    marginVertical: height * 0.012,
    width: "90%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },

  errorText: {
    color: "red",
    fontSize: 14,
    marginTop: 4,
    marginLeft: 4,
  },
});
